import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import './globals.css';
import { Providers } from '~/context';
import { Footer } from '~/components/footer';
import { Header } from '~/components/header';
import { Toolbar } from 'basehub/next-toolbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased w-screen h-screen overflow-hidden bg-slate-1 text-slate-12`}>
        <Providers>
          <div className="max-w-screen-sm mx-auto w-full h-full relative z-[1]">
            <div className="px-5 py-20 flex items-center flex-col gap-[60px]">
              <Header />
              <main className="flex justify-center items-center flex-col gap-[60px]">{children}</main>
              <Footer />
            </div>
          </div>
          <Toolbar />
        </Providers>
      </body>
    </html>
  );
}
